# -*- coding: utf-8 -*-
"""Jihan Luthfiyyah_F0403251045_TTS 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8y-qE1QGe3h1LJJQJXbJVn0OlWmELSZ
"""

def hitung_total(panen_padi, panen_jagung):
    return panen_padi + panen_jagung

total = hitung_total(177, 50)
print("Total hasil panen:", total, "kg")